# Generated by Django 5.0 on 2024-08-28 08:05

import django.db.models.deletion
import social.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkertPlace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_produit', models.CharField(max_length=50, verbose_name='')),
                ('content', models.TextField(max_length=250)),
                ('categorie', models.CharField(max_length=12)),
                ('prix', models.CharField(max_length=8)),
                ('prix_promotion', models.CharField(default='0', max_length=8)),
                ('en_promotion', models.BooleanField(default=False)),
                ('indisponible', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_offre', models.CharField(max_length=50, verbose_name='')),
                ('content', models.TextField(max_length=250)),
                ('categorie', models.CharField(max_length=12)),
                ('indisponible', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=250)),
                ('type', models.CharField(max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageMarkertPlace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=social.models.get_image_upload_path)),
                ('markertPlace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='social.markertplace')),
            ],
        ),
        migrations.CreateModel(
            name='ImageOffre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=social.models.get_image_upload_path)),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='social.offre')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='social.post')),
            ],
        ),
        migrations.CreateModel(
            name='ImagePost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=social.models.get_image_upload_path)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='social.post')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='social.post')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_page', models.CharField(max_length=50, verbose_name="Nom de la page de l'utilisateur")),
                ('pays', models.CharField(max_length=50, verbose_name="pays de l'utilisateur")),
                ('ville', models.CharField(max_length=50, verbose_name="pays de l'utilisateur")),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.profile'),
        ),
        migrations.CreateModel(
            name='PhotProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='profil', verbose_name="Photo de profils de l'utilisateur")),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='social.profile')),
            ],
        ),
        migrations.AddField(
            model_name='offre',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.profile'),
        ),
        migrations.CreateModel(
            name='NomDesFollower',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.profile')),
            ],
        ),
        migrations.CreateModel(
            name='NombreTotalDeFollower',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_follower', models.IntegerField(default=0)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='social.profile')),
            ],
        ),
        migrations.AddField(
            model_name='markertplace',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.profile'),
        ),
        migrations.CreateModel(
            name='ReponseCommentaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='social.commentaire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
